
CREATE DATABASE DevConnect;
GO
CREATE TABLE Usuario(
	Id INT IDENTITY (1, 1) PRIMARY KEY,
	NomeUsuario		NVARCHAR(255)	UNIQUE	NOT NULL,
	NomeCompleto	NVARCHAR(30)			NOT NULL,
	Email			NVARCHAR(255)	UNIQUE	NOT NULL,
	Senha			NVARCHAR(30)			NOT NULL,
	FotoPerfilUrl	NVARCHAR(255)				NULL
);

SELECT * FROM Usuario;

CREATE TABLE Publicacao(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Descricao		NVARCHAR(255) NULL,
	ImagemUrl		NVARCHAR(150) NOT NULL,
	DataPublicacao	DATE NOT NULL,
	IdUsuario		INT NOT NULL FOREIGN KEY REFERENCES Usuario(id)
);

SELECT * FROM Publicacao;


CREATE TABLE Curtida(
    Id              INT IDENTITY (1,1) PRIMARY KEY,
	IdUsuario		INT NOT NULL FOREIGN KEY REFERENCES Usuario(id),
	IdPublicacao	INT NOT NULL FOREIGN KEY REFERENCES Publicacao(id)
);

SELECT * FROM Curtida;


CREATE TABLE Comentario(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdUsuario			INT NOT NULL FOREIGN KEY REFERENCES  Usuario(Id),
	IdPublicacao		INT NOT NULL FOREIGN KEY REFERENCES Publicacao(Id),
	Texto				NVARCHAR(1000) NOT NULL,
	DataComentario		DATE NOT NULL
);
SELECT * FROM Comentario

CREATE TABLE Seguidor(
	IdUsuarioSeguir		INT NOT NULL,
	IdUsuarioSeguidor	INT NOT NULL,

	PRIMARY KEY(IdUsuarioSeguir, IdUsuarioSeguidor)
);
SELECT * FROM Seguidor